language: nix

cache:
  directories:
  - "/nix"

matrix:
  include:
  - env: COMPILER=ghc7103
  - env: COMPILER=ghc801
  - env: COMPILER=ghcjs

script:
- |
  set -eu

  DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
  echo "DIR: $DIR"

  TMPDIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'cache')
  echo "TMPDIR: $TMPDIR"

  echo "*** nix-build ***"
  nix-build -E --option extra-binary-caches https://nixcache.atomic.grump.ly/ "with (import <nixpkgs> {}); pkgs.haskell.packages.$COMPILER.callPackage ./default.nix { }"
  echo "*** nix-built ***"

  trap "rm -rf \"$TMPDIR\"" EXIT

  echo "SUBSHELL"

  cd "$DIR"

  echo "Stripping (System|Deriver)"
  for i in "$TMPDIR/"*.narinfo; do
    [ -f "$i" ] || break
    echo "Stripping narinfo: $i"
    sed -e '/^\(System\|Deriver\): /d' "$i" > "$i.new"
    mv -- "$i.new" "$i"
  done

  echo "Uploading cache."
  nix-shell $NIXOPTS -E 'with import <nixpkgs> {}; runCommand "shell" { buildInputs = [ awscli ]; } ""' --run "HOME=/var/empty aws s3 sync --size-only --cache-control 'public, max-age=315360000' --expires 'Tue, 01 Feb 2050 00:00:00 GMT' '$TMPDIR/' s3://nixcache.atomic.grump.ly/"

  echo "nix-collect-garbage"
  nix-collect-garbage -d

env:
  global:
  - secure: TUi8CK5GeaGSXG4EpqOzJOWHlhWYDFkEDRrpbO3DcVDYgHyRbcC6cFEvwUzTNVS8P1wZoe/26kGq+bgnTea5JCFnubZWH16Qsif/5YJpjCtS10S7Gt+gJOvXAFbCeyxRDP6TgjDJFgqYfpeng/OJqTiaR1dA0P8nxQfCmtmmplkvUPfnMNz8w92Y1HgsCFopKjQJg+Pm8+4iWEmuCNS/eZZ8GcZhKrQauYTB03GaCpu7M5FYk7Ux2FdzQEypjPG7IrtQAF1pGVUXPSvyRXawwLIrjTFu94hqdqaWHbbSf9uKIwdM77TbtVQ+rHSe5YPA2PGnAB7GmxR0JPi3m0+Kg85Mla8xp2xEFDHpSYv51Gq4B0MKDKgIc+MPdRi38SDyPk6FYVCe669Lm6/yyam03B31Xd9lV1DKzYVO7vFEbNx6mxYx5dZpbfWChXsOcbBISDJ7Kob6qhCXeYlE5SoxCclcJF+vAj2v0Yw+CnbuuKrpEmysbO+xmpae1s1D/4ykAXHDa+ZsqiSoK93jRc0Yjcebq0fdAwweABCpRueeW9i7uj9upPGd89UCOq2zFJ9KtCM02cCVzDN+e+SVFYa95g31Z9zQ/FcCiOfKolgMf0q72bHsLII0DWxzxZQrw0D617ffA4nCtijG1qI9vcHkQ1A8ht4Tt1+sXTw+6x7jUkc=
  - secure: Fzz2IspMowfDF+/u5gTVJXJOLamr12BKjfKxoLIA+E0+QxLBwdXjM5HRVut5qCaE67df0xC4tMh9KQxT2qT227vv+7E6Pa2jzW2m5CqQEwPUo2o372eS6kK66XzEwoMRPT+Wbl7u+1oLpdDa0JaSBnm9cMtiigx5vxcVqFe1f5pbwy0ywj31VEYllada/zDGyW0MEhG1rehBNctqno2NaBw/6nToiJf2bX80wLrcTXyvNn0DGe+dJ3y0tzVTzXVCtJ0Q1AfVvYEUFWMZXM89lkB+kofxy/Gp52xtN74D3c3cbdFoFJX/wVtUjCb9cAE2hwVhl1A+6eoqtsMP8eK7Ic1TuAgF+vSVtCN8LBVbnWDQRlKno35nQqjRafLvej1dfRDBaa7sjEVOSANsYzwrrwdRsTGdhBvPcGUMYPZ/MKSZyLg6HBP7Q1OzXEoynIpmhZoAjlpvtDAwrvOGsF86EXnhSPY0cnZBu1SGwutJkclvJykkks1Bg0dgWDojjwxHcNOUYzROX6iSok3FnARGrgxgwXtGhnYN/V8gksvVFfTbkxdmyV9F3mUT+j19F6XHZf2IV7DJSArj80dW8YKuJ0ZSK+jRmJAzKloegcuE0aUMjtQjIGKpJiDjHby/OBaR3nwsIyKp9WzOCuyeQJO/fAq9IGZ/9hgSh2LJdKVDXaM=
