language: nix

cache:
  directories:
  - "/nix"

env:
  - COMPILER=ghc7103
  - COMPILER=ghc801
  - COMPILER=ghcjs

script: nix-build -E 'with import <nixpkgs> { }; import ./default.nix { compiler= "$COMPILER"; }'
