language: nix

cache:
  directories:
  - "/nix"

matrix:
  include:
  - script: nix-build -E 'with import <nixpkgs> { }; import ./default.nix { compiler= "ghc7103"; }'
  - script: nix-build -E 'with import <nixpkgs> { }; import ./default.nix { compiler= "ghc801"; }'
  - script: nix-build -E 'with import <nixpkgs> { }; import ./default.nix { compiler= "ghcjsHEAD"; }'


